version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/business_lookup
      - SECRET_KEY=${SECRET_KEY}
      - APOLLO_API_KEY=${APOLLO_API_KEY}
      - VECTORSHIFT_API_KEY=${VECTORSHIFT_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - LINKEDIN_API_KEY=${LINKEDIN_API_KEY}
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=business_lookup
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
